---
version: '3.9'
name: azurite
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: "azurite"
    hostname: azurite
    entrypoint: ["azurite", "--blobHost", "0.0.0.0", "--queueHost", "0.0.0.0", "--tableHost", "0.0.0.0", "-l", "data"]
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002" 
    volumes:
      - "c:/Users/conta/.azurite:/opt/azurite/data"